config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'badges/index'
  get 'badges/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :badges, only: %i[index show]

  resources :feedback, only: %i[new create]

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges

    resources :gists, only: :index

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/gist.rb
# frozen_string_literal: true

class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :url, presence: true
end

app/controllers/admin/gists_controller.rb
# frozen_string_literal: true

# Admin::GistsController < Admin::BaseController
class Admin::GistsController < Admin::BaseController
  def index
    @gists = Gist.all
  end
end

app/views/admin/gists/_gist.html.slim
tr
  th scope="row"= link_to truncate(gist.question.body, length: 25, escape: false), admin_question_path(gist)
  td= link_to gist.url, gist.url, target: '_blank'
  td= gist.user&.email

app/views/admin/gists/index.html.slim
.row
  .col
    - if @gists.present?
      h2= t('.header')

      table.table.table-sm.table-secondary
        thead.thead-light
          tr
            th scope="col"= Gist.human_attribute_name(:question_id)
            th scope="col"= Gist.human_attribute_name(:url)
            th scope="col"= Gist.human_attribute_name(:user_id)
        tbody= render @gists

    - else
     .alert.alert-warning role="alert"= t('.not_records')