config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'badges/index'
  get 'badges/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :badges, only: %i[index show]

  resources :feedback, only: %i[new create]

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges

    resources :gists, only: :index

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/views/shared/_errors.html.slim
- if resource.present? && resource.errors.any?
  = content_tag :div, class: 'resource-errors', data: { resource_id: resource.try(:id) }
    h4
      = t('.header', count: resource.errors.count)
      ':
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/shared/_footer.html.slim
footer
  p
    = current_year
    | . Author: Konstantin. 
  p
    |  Project: 
    = link_to 'TestGuru', github_url('shilovk', 'test-guru')
    | . About project: Tests with categories, questions, answers, users. 
    = link_to 'Учебный проект в онлайн-школе Thinknetica', 'thinknetica.com'

app/views/shared/_nav.html.slim
nav.navbar.navbar-light.bg-light
  .navbar-brand= link_to_unless current_page?(root_url), 'TestGuru', root_path, class: 'navbar-brand'

  - if user_signed_in?
    - if current_user.admin?
      .nav-item= link_to_unless current_page?(admin_tests_url), 'Admin Panel', admin_tests_path, class: 'nav-link'
    .nav-item= link_to_unless current_page?(badges_url), 'Badges', badges_path, class: 'nav-link'


  .nav-item= link_to_unless current_page?(new_feedback_url), 'Feedback', new_feedback_path, class: 'nav-link'

  - if user_signed_in?
    .navbar-text
      .nav-item.d-inline= "Welcome, <b>#{current_user.email}</b> Guru".html_safe
      = link_to t(".sign_out"), destroy_user_session_path, method: :delete, class: 'nav-item nav-link d-inline'
  - else
    - if controller_name != 'registrations'
      = link_to t(".sign_up"), new_user_registration_path, class: 'nav-item nav-link d-inline'
    - if controller_name != 'sessions'
      = link_to t(".sign_in"), new_user_session_path, class: 'nav-item nav-link d-inline'