config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'badges/index'
  get 'badges/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :badges, only: %i[index show]

  resources :feedback, only: %i[new create]

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges

    resources :gists, only: :index

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/views/admin/shared/_nav.html.slim
nav.navbar
  = link_to 'TestGuru', root_path, class: 'navbar-brand'

  .nav-item= link_to_unless current_page?(admin_tests_url), 'Admin Panel', admin_tests_path, class: 'nav-link'
  .nav-item= link_to_unless current_page?(admin_badges_url), 'Badges', admin_badges_path, class: 'nav-link'
  .nav-item= link_to_unless current_page?(admin_gists_url), 'Gists', admin_gists_path, class: 'nav-link'

  .navbar-text
    .nav-item.d-inline= "Welcome, <b>#{current_user.email}</b> Guru".html_safe
    - if controller_name != 'sessions'
      = link_to t(".sign_out"), destroy_user_session_path, method: :delete, class: 'nav-item nav-link d-inline'