config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'badges/index'
  get 'badges/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :badges, only: %i[index show]

  resources :feedback, only: %i[new create]

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :badges

    resources :gists, only: :index

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end
  end
end

app/models/feedback.rb
# frozen_string_literal: true

class Feedback
  include ActiveModel::Model

  attr_accessor :body, :email, :first_name, :phone, :last_name

  validates :body, :first_name, presence: true
  validates :email, presence: true, format: { with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i }

  def to_email
    FeedbackMailer.feedback(self).deliver_now
  end
end

app/controllers/feedback_controller.rb
# frozen_string_literal: true

class FeedbackController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @feedback = Feedback.new
  end

  def create
    @feedback = Feedback.new(feedback_params)
    if @feedback.valid?
      @feedback.to_email
      flash[:notice] = 'Feedback was sent successfuly!'
      redirect_to user_signed_in? ? root_path : new_user_session_path
    else
      render :new
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:body, :email, :first_name, :phone, :last_name)
  end
end

app/views/feedback/new.html.slim
.row.justify-content-center
  .col.col-md-4
    h2= t('.feedback')

    = form_with model: @feedback, url: feedback_index_path, local: true do |f|
      = render 'shared/errors', resource: @feedback

      .card.border-primary
        .card-body.row
          .form-group.p-3
            p
              = f.label :body
              = f.text_area :body, autofocus: true, class: 'form-control'

            p
              = f.label :email
              = f.email_field :email, autocomplete: "email", class: 'form-control'

            p
              = f.label :first_name
              = f.text_area :first_name, class: 'form-control'

            p
              = f.label :last_name
              = f.text_area :last_name, class: 'form-control'

            p
              = f.label :phone
              = f.text_field :phone, class: 'form-control'

            p= f.submit 'Send', class: 'btn btn-primary'